### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/http-music#1]
Officially named `http-music`. On temporary(?) name change to `ncmpcmagpagcagpp` (Node Cool Music Player - Cool Music And Good Player And Good Cool And Good!(++)).

/cc everyone at https://github.com/towerofnix/tlnccuwagnf/issues/5 (@BookOwl, @kvackkvack, @heyitsmeuralex, @eq)

**Comment by towerofnix** [comment]
Pronunciations also appreciated!

**Comment by eq** [comment]
>temporary

nah

**Comment by towerofnix** [comment]
`http-music`:

* Distinguishes that it can download music from the internets.
* Confusing, though -- this makes it sound like this project is a music *server*, not a music *player*.
* And I mostly use it for the music on my *own* computer because of its handy playlist-filtering tools (and also because I made it and it's the only good free music player :tada:).
  * Then again, the fact that it can play music from an HTTP server *is* really handy; I often use it to play the music that's on my computer on my raspberry pi or on a laptop in a different room.

**Comment by eq** [comment]
`ncmpcmagpagcagpp`:
- Fits to the naming style of ncmpcpp, for less confusion
- Not confusing at all (it's cool and good, and is a music player, and is also good and cool and ++)
- Can be pronounced many different ways

**Comment by towerofnix** [comment]
`music-player`:

* Boring, undescriptive
* Everybody's taken it, so - conflicts
* Help

**Comment by BookOwl** [comment]
`tonic-mp`
Tower Of Nix's Incredibly Cool Music Player

**Comment by heyitsmeuralex** [comment]
```
K incredibly
E awesome
K music player by tonix
```

**Comment by heyitsmeuralex** [comment]
> ncmpcmagpagcagpp

official pronounciation:

**en - comp - see - magpag - cah - gap**

**Comment by kvackkvack** [comment]
`XMLHttpMusicPlayer` :^)

**Comment by heyitsmeuralex** [comment]
@kvackkvack we need a Delet This emoji on gh

**Comment by bwbw223** [comment]
[Resolved?]

**Comment by towerofnix** [comment]
"Yes" as in "I will definitely never change it", but definitely not a resolved problem :) - though closed anyways!

**Comment by 109C** [comment]
Man, I was really looking forwards to `XMLHttpMusicPlayer` :(

**Comment by towerofnix** [comment]
Alas. :broken_heart:
